spring:
  servlet:
    multipart:
      max-file-size: 250MB
      max-request-size: 30MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meetty
    username: postgres
    password: "password"
    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false